razorpay:
  key:
    id: ${RAZORPAY_KEY_ID}
    secret: ${RAZORPAY_KEY_SECRET}

server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Productdb
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 8MB

app:
  upload:
    dir: uploads
  base-url: http://localhost:8080
